In [1]:
import numpy as np
from PIL import Image

### Numpy Array

In [9]:
a = np.array([2, 3, 4])   # Create array(1D) from python list
print(a[0])               # Access elements using square brackets

a[1] = 5
print(a)

b = np.array([
    [2,3,4],
    [5,6,7]
])
print(b[1,1])

b[1,1] = 10
print(b)

c = np.array([
    [1.5, 3.21, 5.79],
    [6.12, 7.93, 10.5]
])
print(c[1,0])


2
[2 5 4]
6
[[ 2  3  4]
 [ 5 10  7]]
6.12
