In [2]:
import numpy as np
from PIL import Image

### Numpy Array

In [3]:
a = np.array([2, 3, 4])   # Create array(1D) from python list
print(a[0])               # Access elements using square brackets

a[1] = 5
print(a)

b = np.array([
    [2,3,4],
    [5,6,7]
])
print(b[1,1])

b[1,1] = 10
print(b)

c = np.array([
    [1.5, 3.21, 5.79],
    [6.12, 7.93, 10.5]
])
print(c[1,0])


2
[2 5 4]
6
[[ 2  3  4]
 [ 5 10  7]]
6.12


In [4]:
print(a.ndim)             # Prints "1"
print(b.ndim)             # Prints "2"

print(a.shape)            # Prints "(3,)"
print(b.shape)            # Prints "(2, 3)"

print(a.size)             # Prints "3"
print(b.size)             # Prints "6"

print(a.dtype)            # Prints "int32"
print(c.dtype)            # Prints "float64"

1
2
(3,)
(2, 3)
3
6
int32
float64


In [5]:
a = np.zeros((3,3))
print(a)

b = np.ones((3,2))
print(b)

c = np.full((3,3),8)
print(c)

d = np.eye(3)
print(d)

e = np.random.random((3,3))
print(e)

f = np.arange(5)
print(f)

g = np.linspace(6,11,5)
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.73256402 0.96423335 0.51098723]
 [0.39837954 0.64684801 0.85836944]
 [0.5949214  0.38283642 0.28747562]]
[0 1 2 3 4]
[ 6.    7.25  8.5   9.75 11.  ]


In [6]:
a = np.arange(10)**3     # In python "**" means power x**3 = x^3
print(a)                 # Prints "[0 1 8 27 64 125 216 343 512 729]"

print(a[2])              # Prints "8"
print(a[2:5])            # Prints "[8 27 64]"
print(a[:6])             # Prints "[0 1 8 27 64 125]"
print(a[2:])             # Prints "[8 27 64 125 216 343 512 729]"
print(a[::-1])           # Prints reversed array

a[:6:2] = 1000           # From start to position 6 (exclusive) set every 2nd element to 1000
print(a)                 # Prints "[1000 1 1000 27 1000 125 216 343 512 729]"

# Iterating over array
for element in a:
  print(element**(1/3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[  0   1   8  27  64 125]
[  8  27  64 125 216 343 512 729]
[729 512 343 216 125  64  27   8   1   0]
[1000    1 1000   27 1000  125  216  343  512  729]
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998
