In [1]:
import numpy as np
from PIL import Image

### Numpy Array

In [9]:
a = np.array([2, 3, 4])   # Create array(1D) from python list
print(a[0])               # Access elements using square brackets

a[1] = 5
print(a)

b = np.array([
    [2,3,4],
    [5,6,7]
])
print(b[1,1])

b[1,1] = 10
print(b)

c = np.array([
    [1.5, 3.21, 5.79],
    [6.12, 7.93, 10.5]
])
print(c[1,0])


2
[2 5 4]
6
[[ 2  3  4]
 [ 5 10  7]]
6.12


In [ ]:
print(a.ndim)             # Prints "1"
print(b.ndim)             # Prints "2"

print(a.shape)            # Prints "(3,)"
print(b.shape)            # Prints "(2, 3)"

print(a.size)             # Prints "3"
print(b.size)             # Prints "6"

print(a.dtype)            # Prints "int32"
print(c.dtype)            # Prints "float64"

1
2
(3,)
(2, 3)
3
6
int32
float64


In [32]:
a = np.zeros((3,3))
print(a)

b = np.ones((3,2))
print(b)

c = np.full((3,3),8)
print(c)

d = np.eye(3)
print(d)

e = np.random.random((3,3))
print(e)

f = np.arange(5)
print(f)

g = np.linspace(6,11,5)
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.16430364 0.68614076 0.87324271]
 [0.47733735 0.39853405 0.74793818]
 [0.49674189 0.11357168 0.66870557]]
[0 1 2 3 4]
[ 6.    7.25  8.5   9.75 11.  ]
