In [33]:
import numpy as np
from PIL import Image

### Numpy Array

In [34]:
a = np.array([2, 3, 4])   # Create array(1D) from python list
print(a[0])               # Access elements using square brackets

a[1] = 5
print(a)

b = np.array([
    [2,3,4],
    [5,6,7]
])
print(b[1,1])

b[1,1] = 10
print(b)

c = np.array([
    [1.5, 3.21, 5.79],
    [6.12, 7.93, 10.5]
])
print(c[1,0])


2
[2 5 4]
6
[[ 2  3  4]
 [ 5 10  7]]
6.12


In [35]:
print(a.ndim)             # Prints "1"
print(b.ndim)             # Prints "2"

print(a.shape)            # Prints "(3,)"
print(b.shape)            # Prints "(2, 3)"

print(a.size)             # Prints "3"
print(b.size)             # Prints "6"

print(a.dtype)            # Prints "int32"
print(c.dtype)            # Prints "float64"

1
2
(3,)
(2, 3)
3
6
int32
float64


In [36]:
a = np.zeros((3,3))
print(a)

b = np.ones((3,2))
print(b)

c = np.full((3,3),8)
print(c)

d = np.eye(3)
print(d)

e = np.random.random((3,3))
print(e)

f = np.arange(5)
print(f)

g = np.linspace(6,11,5)
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.36070755 0.47945532 0.25888595]
 [0.77416108 0.55424842 0.66900245]
 [0.41353091 0.87023191 0.6161025 ]]
[0 1 2 3 4]
[ 6.    7.25  8.5   9.75 11.  ]


In [37]:
a = np.arange(10)**3     # In python "**" means power x**3 = x^3
print(a)                 # Prints "[0 1 8 27 64 125 216 343 512 729]"

print(a[2])              # Prints "8"
print(a[2:5])            # Prints "[8 27 64]"
print(a[:6])             # Prints "[0 1 8 27 64 125]"
print(a[2:])             # Prints "[8 27 64 125 216 343 512 729]"
print(a[::-1])           # Prints reversed array

a[:6:2] = 1000           # From start to position 6 (exclusive) set every 2nd element to 1000
print(a)                 # Prints "[1000 1 1000 27 1000 125 216 343 512 729]"

# Iterating over array
for element in a:
  print(element**(1/3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[  0   1   8  27  64 125]
[  8  27  64 125 216 343 512 729]
[729 512 343 216 125  64  27   8   1   0]
[1000    1 1000   27 1000  125  216  343  512  729]
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [38]:
b = np.array([[ 0,  1,  2,  3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

print(b[2, 3])           # Prints "23"

print(b[:, 1])           # Print second column of b
print(b[:, 1:3])         # Print second and third column of b
print(b[:2, 2])          # Print first 2 rows in the third column of b
print(b[-2:, 1])         # Print last 2 rows in the second column of b
print(b[1:4, 2])         # Print rows 2-4 in the third column of b

print()

print(b[3, :])           # Print fourth row of b
print(b[1:3, :])         # Print second and third row of b
print(b[2, :2])          # Print first 2 columns in the third row of b
print(b[1, -2:])         # Print last 2 columns in the second row of b
print(b[2, 1:4])         # Print columns 2-4 in the third row of b

# Iterating over 2D array
for row in b:
  for col in row:
    print(col, end=' ')
  print()

23
[ 1 11 21 31 41]
[[ 1  2]
 [11 12]
 [21 22]
 [31 32]
 [41 42]]
[ 2 12]
[31 41]
[12 22 32]

[30 31 32 33]
[[10 11 12 13]
 [20 21 22 23]]
[20 21]
[12 13]
[21 22 23]
0 1 2 3 
10 11 12 13 
20 21 22 23 
30 31 32 33 
40 41 42 43 


In [39]:
a = np.array([
    [1,2], 
    [3, 4], 
    [5, 6]
])
# [0,1,2] is row index [0,1,0] is column index
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [40]:
a = np.array([
    [1,2,3], 
    [4,5,6], 
    [7,8,9], 
    [10, 11, 12]
])

# Create an array of indices of the column
b = np.array([0, 2, 0, 1])
# np.arrange(4) array of indexes of rows
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [41]:
a = np.array([
    [1,2], 
    [3, 4], 
    [5, 6]
])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])   # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])      # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### Changing the shape of an array

In [42]:
a = np.floor(10 * np.random.random((3, 4)))
print(a)

print(a.ravel())      # prints the array, flattened
print(a.reshape(6, 2))# prints the array with a modified shape

[[4. 1. 7. 2.]
 [3. 8. 3. 7.]
 [4. 0. 9. 5.]]
[4. 1. 7. 2. 3. 8. 3. 7. 4. 0. 9. 5.]
[[4. 1.]
 [7. 2.]
 [3. 8.]
 [3. 7.]
 [4. 0.]
 [9. 5.]]


### Stacking together different arrays

In [43]:
# Create two random integer array
# elements are in range of 1 to 10
a = np.random.randint(low=1, high=10, size=(2,2))
b = np.random.randint(low=1, high=10, size=(2,2))

c = np.vstack((a, b))       # Vertically stack a and b
print(c)                    # Will print vertically stacked array

d = np.hstack((a, b))       # Horizontally stack a and b
print(d)                    # Will print horizontally stacked array

[[4 4]
 [7 1]
 [1 4]
 [8 5]]
[[4 4 1 4]
 [7 1 8 5]]


In [44]:
# For 2D array
a = np.random.randint(low=1, high=10, size=(2,2))
b = np.random.randint(low=1, high=10, size=(2,2))
print(a)
print(b)
# for any 2D array column stack will acts like hstack
c = np.column_stack((a, b))
print(c)                     # Will print horizontally stacked array

# For 1D array its just converts rows to colum 
a = np.array([4., 2., 5.])
b = np.array([3., 8., 10])

c = np.column_stack((a, b))  # returns a 2D array
print(c)                     # Prints [[4. 3.]
                             #         [2. 8.]
                             #         [5, 10]]

[[6 1]
 [2 3]]
[[8 1]
 [6 2]]
[[6 1 8 1]
 [2 3 6 2]]
[[ 4.  3.]
 [ 2.  8.]
 [ 5. 10.]]


In [45]:
## Row stack

a = np.random.randint(low=1, high=9, size=(3,3))
b = np.random.randint(low=10, high=19, size=(3,3))
print(a)
print(b)

c = np.row_stack((a,b))
print(c)

[[6 1 3]
 [7 4 2]
 [4 3 8]]
[[18 13 17]
 [16 18 12]
 [11 14 10]]
[[ 6  1  3]
 [ 7  4  2]
 [ 4  3  8]
 [18 13 17]
 [16 18 12]
 [11 14 10]]


In [46]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Elementwise sum
print(x + y)            # Operator overloading
print(np.add(x, y))     # Function in numpy module

# Elementwise difference
print(x - y)            # Operator overloading
print(np.subtract(x, y))# Function in numpy module

# Elementwise product
print(x * y)            # Operator overloading
print(np.multiply(x, y))# Function in numpy module

# Elementwise division
print(x / y)            # Operator overloading
print(np.divide(x, y))  # Function in numpy module

# Elementwise power
print(x**2)             # Operator overloading
print(np.power(x, 2))   # Function in numpy module

# Elementwise square root
print(x**(1/2.))        # Operator overloading
print(np.sqrt(x))       # Function in numpy module

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 1  4]
 [ 9 16]]
[[ 1  4]
 [ 9 16]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [47]:
a = np.arange(5)
print(a)

print(np.exp(a))
print(np.sin(a))
print(np.tan(a))

[0 1 2 3 4]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128]


In [48]:
a = np.random.randint(10, size = (3,3))
print(a)
print(a.sum()) # sum of the whole array
print(a.min()) # min value of the whole array
print(a.max()) # max value of the whole array


[[1 0 4]
 [7 6 4]
 [3 2 5]]
32
0
7


In [51]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
# axis = 0 means column
# axis = 1 means row
print(x.sum(axis=0)) # sum of each colum 
print(x.min(axis=1)) # min values of each row
print(x.cumsum(axis=0)) # cumulative sum of each column

[15 18 21 24]
[1 5 9]
[[ 1  2  3  4]
 [ 6  8 10 12]
 [15 18 21 24]]
