#### **Homework 01:**
Generate random matrix of size 10 x 5. Then, solve the following problems:

In [1]:
import numpy as np

In [3]:
m = np.random.randint(low=1, high=10, size=(10,5))
print("10 x 5 random Matrix: \n", m)

10 x 5 random Matrix: 
 [[5 6 6 1 7]
 [5 3 5 7 6]
 [7 7 5 3 7]
 [8 5 3 2 2]
 [9 7 9 1 3]
 [8 6 5 8 7]
 [2 8 1 7 4]
 [2 9 4 6 1]
 [7 7 1 8 3]
 [7 6 6 9 6]]


##### **Problem 01:**
Calculate the sum and mean of the 2nd row of the matrix.

In [4]:
sum = m[1].sum()
print("Sum the 2nd row of the matrix : ", sum)
mean = sum / len(m[1])
print("The mean of the 2nd row of the matrix:", mean)

Sum the 2nd row of the matrix :  26
The mean of the 2nd row of the matrix: 5.2


## Problem - 3
